apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-backend-post-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-backend-post
  template:
    metadata:
      labels:
        app: k8s-backend-post
    spec:
      containers:
        - name: k8s-backend-post
          image: goozip2/k8s-backend-post:0.0.1
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080


          volumeMounts:
            - mountPath: /etc/config
              name: backend-post-config-volume
              readOnly: true
            - mountPath: /etc/secret
              name: backend-post-secret-volume
              readOnly: true

      volumes:
        - name: backend-post-config-volume
          configMap:
            name: backend-post-config
            items:
              - key: application-dev.yml
                path: application-dev.yml
        - name: backend-post-secret-volume
          secret:
            secretName: backend-post-secret
            items:
              - key: application-secret.yml
                path: application-secret.yml